CREATE TABLE IF NOT EXISTS revinfo
(
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

create sequence if not exists revinfo_seq start with 1 increment by 50;

CREATE TABLE IF NOT EXISTS tb_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_cadastro    TIMESTAMP(6),
    id_cliente     BIGINT         NOT NULL,
    id_restaurante BIGINT         NOT NULL,
    id_cardapio    BIGINT         NOT NULL,
    valor          NUMERIC(13, 2) NOT NULL,
    status_code    INTEGER,
    response_code  INTEGER
);

CREATE TABLE IF NOT EXISTS tb_pedido_aud
(
    id             BIGINT         NOT NULL,
    rev            INTEGER        NOT NULL,
    revtype        SMALLINT,
    dt_cadastro    TIMESTAMP(6),
    id_cliente     BIGINT         NOT NULL,
    id_restaurante BIGINT         NOT NULL,
    id_cardapio    BIGINT         NOT NULL,
    valor          NUMERIC(13, 2) NOT NULL,
    status_code    INTEGER,
    response_code  INTEGER,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_pedido_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
