CREATE TABLE IF NOT EXISTS revinfo
(
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

create sequence if not exists revinfo_seq start with 1 increment by 50;

CREATE TABLE IF NOT EXISTS tb_pedido
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_cadastro    TIMESTAMP(6),
    id_cliente     BIGINT         NOT NULL,
    id_restaurante BIGINT         NOT NULL,
    valor_total    NUMERIC(13, 2) NOT NULL,
    status_code    INTEGER,
    response_code  INTEGER
);

CREATE TABLE IF NOT EXISTS tb_pedido_aud
(
    id             BIGINT         NOT NULL,
    rev            INTEGER        NOT NULL,
    revtype        SMALLINT,
    dt_cadastro    TIMESTAMP(6),
    id_cliente     BIGINT         NOT NULL,
    id_restaurante BIGINT         NOT NULL,
    valor_total    NUMERIC(13, 2) NOT NULL,
    status_code    INTEGER,
    response_code  INTEGER,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_pedido_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_item_pedido
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido   BIGINT         NOT NULL,
    id_cardapio BIGINT         NOT NULL,
    qtd         INTEGER        NOT NULL,
    valor       NUMERIC(13, 2) NOT NULL,

    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (id_pedido) REFERENCES tb_pedido (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tb_item_pedido_aud
(
    id          BIGINT  NOT NULL,
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id_pedido   BIGINT,
    id_cardapio BIGINT,
    qtd         INTEGER,
    valor       NUMERIC(13, 2),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_item_pedido_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
