CREATE TABLE IF NOT EXISTS revinfo (
                                       rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       revtstmp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_perfil (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         nome VARCHAR(20) NOT NULL CONSTRAINT uk_perfil_nome UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_perfil_aud (
                                             id BIGINT NOT NULL,
                                             rev INTEGER NOT NULL,
                                             revtype SMALLINT,
                                             nome VARCHAR(20),
                                             PRIMARY KEY (id, rev),
                                             CONSTRAINT fk_perfil_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_cliente (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          nome VARCHAR(50) NOT NULL,
                                          cpf VARCHAR(20) NOT NULL,
                                          email VARCHAR(50) NOT NULL,
                                          senha VARCHAR(255) NOT NULL,
                                          dt_cadastro TIMESTAMP(6),
                                          id_perfil BIGINT,
                                          CONSTRAINT fk_cliente_perfil FOREIGN KEY (id_perfil) REFERENCES tb_perfil(id),
                                          CONSTRAINT uk_cliente_cpf_email UNIQUE (cpf, email)
);

CREATE TABLE IF NOT EXISTS tb_cliente_aud (
                                              id BIGINT NOT NULL,
                                              rev INTEGER NOT NULL,
                                              revtype SMALLINT,
                                              nome VARCHAR(50),
                                              cpf VARCHAR(20),
                                              email VARCHAR(50),
                                              senha VARCHAR(255),
                                              dt_cadastro TIMESTAMP(6),
                                              id_perfil BIGINT,
                                              PRIMARY KEY (id, rev),
                                              CONSTRAINT fk_cliente_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_endereco (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           rua VARCHAR(100) NOT NULL,
                                           bairro VARCHAR(50) NOT NULL,
                                           cep VARCHAR(10) NOT NULL,
                                           cidade VARCHAR(50) NOT NULL,
                                           uf VARCHAR(2) NOT NULL,
                                           numero VARCHAR(10),
                                           complemento VARCHAR(50),
                                           principal BOOLEAN NOT NULL,
                                           observacao TEXT,
                                           id_cliente BIGINT NOT NULL,
                                           CONSTRAINT fk_endereco_cliente FOREIGN KEY (id_cliente) REFERENCES tb_cliente(id)
);

CREATE TABLE IF NOT EXISTS tb_endereco_aud (
                                               id BIGINT NOT NULL,
                                               rev INTEGER NOT NULL,
                                               revtype SMALLINT,
                                               rua VARCHAR(100),
                                               bairro VARCHAR(50),
                                               cep VARCHAR(10),
                                               cidade VARCHAR(50),
                                               uf VARCHAR(2),
                                               numero VARCHAR(10),
                                               complemento VARCHAR(50),
                                               principal BOOLEAN,
                                               observacao TEXT,
                                               id_cliente BIGINT,
                                               PRIMARY KEY (id, rev),
                                               CONSTRAINT fk_endereco_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);


create sequence if not exists revinfo_seq start with 1 increment by 50;

INSERT INTO tb_perfil (nome)
SELECT 'ROLE_CLIENTE'
WHERE NOT EXISTS (
    SELECT 1 FROM tb_perfil WHERE nome = 'ROLE_CLIENTE'
);