CREATE TABLE IF NOT EXISTS revinfo
(
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_perfil
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(20) NOT NULL
        CONSTRAINT uk_perfil_nome UNIQUE
);

CREATE TABLE IF NOT EXISTS tb_perfil_aud
(
    id      BIGINT  NOT NULL,
    rev     INTEGER NOT NULL,
    revtype SMALLINT,
    nome    VARCHAR(20),
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_perfil_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_usuario
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(50)  NOT NULL,
    cpf         VARCHAR(20)  NOT NULL,
    email       VARCHAR(50)  NOT NULL,
    senha       VARCHAR(255) NOT NULL,
    dt_cadastro TIMESTAMP(6),
    id_perfil   BIGINT,
    CONSTRAINT fk_usuario_perfil FOREIGN KEY (id_perfil) REFERENCES tb_perfil (id),
    CONSTRAINT uk_usuario_cpf_email UNIQUE (cpf, email)
);

CREATE TABLE IF NOT EXISTS tb_usuario_aud
(
    id          BIGINT  NOT NULL,
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    nome        VARCHAR(50),
    cpf         VARCHAR(20),
    email       VARCHAR(50),
    senha       VARCHAR(255),
    dt_cadastro TIMESTAMP(6),
    id_perfil   BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_usuario_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_tipo_cozinha
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao varchar(1000) NULL,
    nome      varchar(50)   NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_tipo_cozinha_aud
(
    id        BIGINT        NOT NULL,
    rev       INTEGER       NOT NULL,
    revtype   SMALLINT,
    descricao varchar(1000) NULL,
    nome      varchar(50)   NULL,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_tipo_cozinha_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_restaurante
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao             varchar(1000) NULL,
    nome                  varchar(50)   NOT NULL,
    horario_funcionamento VARCHAR(500)  NOT NULL,
    id_tipo_cozinha       BIGINT        NOT NULL,
    id_usuario            BIGINT        NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_restaurante_aud
(
    id                    BIGINT        NOT NULL,
    rev                   INTEGER       NOT NULL,
    revtype               SMALLINT,
    descricao             varchar(1000) NULL,
    nome                  varchar(50)   NULL,
    horario_funcionamento VARCHAR(500)  NULL,
    id_tipo_cozinha       BIGINT        NULL,
    id_usuario            BIGINT        NULL,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_restaurante_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_endereco
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua            VARCHAR(100) NOT NULL,
    bairro         VARCHAR(50)  NOT NULL,
    cep            VARCHAR(10)  NOT NULL,
    cidade         VARCHAR(50)  NOT NULL,
    uf             VARCHAR(2)   NOT NULL,
    numero         VARCHAR(10),
    complemento    VARCHAR(50),
    observacao     TEXT,
    id_restaurante BIGINT       NOT NULL,
    CONSTRAINT fk_endereco_restaurante FOREIGN KEY (id_restaurante) REFERENCES tb_restaurante (id)
);

CREATE TABLE IF NOT EXISTS tb_endereco_aud
(
    id             BIGINT  NOT NULL,
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    rua            VARCHAR(100),
    bairro         VARCHAR(50),
    cep            VARCHAR(10),
    cidade         VARCHAR(50),
    uf             VARCHAR(2),
    numero         VARCHAR(10),
    complemento    VARCHAR(50),
    observacao     TEXT,
    id_restaurante BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_endereco_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE IF NOT EXISTS tb_cardapio
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           varchar(50)    NOT NULL,
    descricao      varchar(1000)  NULL,
    preco          numeric(19, 2) NOT NULL,
    foto           varchar(2000)  NULL,
    disponivel     bool           NOT NULL,
    id_restaurante BIGINT         NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_cardapio_aud
(
    id             BIGINT         NOT NULL,
    rev            INTEGER        NOT NULL,
    revtype        SMALLINT,
    nome           varchar(50)    NULL,
    descricao      varchar(1000)  NULL,
    preco          numeric(19, 2) NULL,
    foto           varchar(2000)  NULL,
    disponivel     bool           NULL,
    id_restaurante BIGINT,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_cardapio_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

create sequence if not exists revinfo_seq start with 1 increment by 50;

INSERT INTO tb_perfil (nome)
SELECT 'ROLE_FUNCIONARIO'
WHERE NOT EXISTS (SELECT 1
                  FROM tb_perfil
                  WHERE nome = 'ROLE_FUNCIONARIO');

INSERT INTO tb_perfil (nome)
SELECT 'ROLE_DONO'
WHERE NOT EXISTS (SELECT 1
                  FROM tb_perfil
                  WHERE nome = 'ROLE_DONO');
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM tb_tipo_cozinha) THEN

            INSERT INTO tb_tipo_cozinha (nome, descricao)
            VALUES ('Italiana',
                    'Massas artesanais, risotos e pizzas clássicas com foco em ingredientes frescos e molhos tradicionais.'),
                   ('Japonesa',
                    'Culinária focada em peixes frescos, sushis, sashimis, ramens e técnicas milenares de preparo.'),
                   ('Brasileira',
                    'Diversidade regional com pratos como feijoada, churrasco, moquecas e ingredientes típicos do Brasil.'),
                   ('Mexicana',
                    'Sabores intensos e picantes com tacos, burritos, guacamoles e temperos à base de pimenta e milho.'),
                   ('Francesa',
                    'Gastronomia refinada com foco em técnicas clássicas, molhos complexos, queijos e alta confeitaria.'),
                   ('Chinesa',
                    'Variedade de pratos feitos no wok, dim sum, yakisoba e o equilíbrio entre sabores doces e salgados.'),
                   ('Árabe',
                    'Pratos tradicionais como homus, quibes, esfirras e kaftas, marcados pelo uso de especiarias e azeite.'),
                   ('Indiana',
                    'Explosão de aromas com currys, massalas, pães naan e grande foco em pratos vegetarianos e temperados.'),
                   ('Portuguesa',
                    'Baseada em frutos do mar, bacalhau, azeites de oliva, pães e a famosa doçaria conventual.'),
                   ('Tailandesa',
                    'Harmonização entre doce, salgado, azedo e picante, com uso frequente de leite de coco e ervas frescas.'),
                   ('Americana',
                    'Famosa pelos hambúrgueres artesanais, churrasco (BBQ), tortas e porções generosas de comfort food.'),
                   ('Espanhola',
                    'Destaque para paellas, tapas variadas, frutos do mar e o uso característico de açafrão e pimentão.'),
                   ('Vegetariana',
                    'Culinária focada em vegetais, grãos e leguminosas, priorizando alimentação saudável e sem carne.'),
                   ('Mediterrânea',
                    'Dieta equilibrada com foco em legumes, peixes, azeite de oliva, grãos integrais e ervas naturais.'),
                   ('Peruana',
                    'Conhecida pelos ceviches frescos, pratos à base de milho, batatas e a fusão de sabores andinos.'),
                   ('Coreana',
                    'Pratos fermentados como o kimchi, churrasco coreano (bulgogi) e temperos intensos e picantes.'),
                   ('Argentina',
                    'Especializada em cortes de carne bovina grelhada na parrilla, empanadas e acompanhamentos rústicos.'),
                   ('Alemã',
                    'Pratos rústicos com salsichas, joelho de porco (eisbein), chucrute, batatas e molhos encorpados.'),
                   ('Vegana',
                    'Gastronomia estritamente baseada em plantas, livre de qualquer produto ou subproduto de origem animal.'),
                   ('Contemporânea',
                    'Fusão de diferentes técnicas e ingredientes globais com apresentações modernas e receitas autorais.');

        END IF;
    END
$$;