quarkus.http.port=9094

# RabbitMQ Connection
rabbitmq-host=localhost
rabbitmq-port=5672

# Canal de ENTRADA (Lê o que o Pedido enviou)
mp.messaging.incoming.pedido-recebido.connector=smallrye-rabbitmq
mp.messaging.incoming.pedido-recebido.queue.name=pedido.criado
mp.messaging.incoming.pedido-recebido.exchange.name=pedido.criado

# Canal de SAÍDA (Avisa se o pagamento deu certo ou falhou)
mp.messaging.outgoing.pagamento-finalizado.connector=smallrye-rabbitmq
mp.messaging.outgoing.pagamento-finalizado.exchange.name=pagamento.resultado

mp.messaging.incoming.pedido-recebido.value-deserializer=io.quarkus.jackson.ObjectMapperProducer

# URL da API Externa Procpag
quarkus.rest-client.pagamento-api.url=http://localhost:8089
quarkus.rest-client.pagamento-api.scope=jakarta.inject.Singleton
