rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# Canal de saída para Pedido Criado
mp.messaging.outgoing.pedido-criado.connector=smallrye-rabbitmq
mp.messaging.outgoing.pedido-criado.exchange.name=pedido.criado
mp.messaging.outgoing.pedido-criado.default-routing-key=pedido.criado

# Canal de saída para Pagamento Pendente (usado no Fallback de resiliência)
mp.messaging.outgoing.pagamento-pendente.connector=smallrye-rabbitmq
mp.messaging.outgoing.pagamento-pendente.exchange.name=pagamento.pendente
