quarkus.http.port=9091
quarkus.grpc.server.use-separate-server=false

# ===================================================================
# DATA SOURCE (PostgreSQL)
# ===================================================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:admin}
quarkus.datasource.password=${POSTGRES_PASSWORD:secret}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5434/${POSTGRES_DB:cliente}

# ===================================================================
# HIBERNATE / JPA
# ===================================================================
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.database-generation=validate

# ===================================================================
# FLYWAY
# ===================================================================
quarkus.flyway.enabled=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.default-schema=public
quarkus.flyway.locations=db/migration
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.validate-on-migrate=true

# ===================================================================
# HIBERNATE ENVERS
# ===================================================================
quarkus.hibernate-envers.audit-table-suffix=_aud
quarkus.hibernate-envers.store-data-at-delete=true
quarkus.hibernate-envers.global-with-modified-flag=false
quarkus.hibernate-envers.revision-field-name=rev
quarkus.hibernate-envers.revision-type-field-name=revtype

# ===================================================================
# KEYCLOAK
# ===================================================================
quarkus.oidc.auth-server-url=http://localhost:8180/realms/restaurante-realm
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=s4lkS22kfayLL/diMrkfQArD99+ZBjUndgjFIirUUFw=
quarkus.oidc.application-type=service
quarkus.oidc.discovery-enabled=true
quarkus.oidc.token.issuer=http://localhost:8180/realms/restaurante-realm

# Keycloak Admin Client
keycloak.admin.server-url=http://localhost:8180
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin.target-realm=restaurante-realm
quarkus.keycloak.admin-client.grant-type=password
